---
title: Tables for main manuscript
output:
    word_document:
        df_print: kable
---

```{r, setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
```

```{r counter}
library(dplyr)
library(readr)
library(tidyr)

n <- 0
```

```{r sample_size}
# summary sample size counts for fixed and mr-mega analyis
# break down by cluster for fixed, just show totals for MR-MEGA
sample_size_table_n <- n <- n + 1
summary_table_fixed <- read_csv(here::here("manuscript/tables/meta_analysis_cohort_summary_table_fixed.csv")) |>
  mutate(method = "fixed")
summary_table_mrmega <- read_csv(here::here("manuscript/tables/meta_analysis_cohort_summary_table_mrmega.csv")) |>
  mutate(method = "mrmega") |>
  select(-cluster)

sample_size_table <-
bind_rows(summary_table_fixed, summary_table_mrmega) |>
  pivot_longer(cols = !any_of(c("meta_analysis", "method")),
               names_to = c("cohort", "status"),
               names_sep = "_",
               values_to = "N") |>
  separate(meta_analysis, into = c("meta", "version", "method", "ATC", "Cluster")) |>
  group_by(method, ATC, Cluster, status) |>
  summarize(N = sum(N, na.rm = TRUE)) |>
  pivot_wider(names_from = status, values_from = N) |>
  transmute(ATC, Cluster=if_else(method == "mrmega", true = "MR-MEGA", false = Cluster),
            Cases = cases, Controls = controls, `Neff/2` = round(neff/2, 2)) |>
  ungroup() |>
  select(-method)
```

**Table `r sample_size_table_n`:** Sample sizes for GWAS meta-analyses. Fixed-effects analyses are listed separately for each population cluster (AFR, AMR, EAS, EUR, MID, and SAS) and totals are given for the multi-ancestry analysis (MR-MEGA). Neff/2 = half effective sample size.

```{r sample_size_table}
sample_size_table
```