---
title: Antidepressant exposure GWAS SNP lists for forest plots
output: github_document
---

Requires [SNPlocs.Hsapiens.dbSNP150.GRCh38](https://bioconductor.org/packages/release/data/annotation/html/SNPlocs.Hsapiens.dbSNP150.GRCh38.html) for SNP lookup

```{r lib}
library(readr)
library(dplyr)
library(stringr)
library(SNPlocs.Hsapiens.dbSNP150.GRCh38)
```

List of SNPs from meta-analyses and SusieX
```{r snps}
metaset <- "antidep-2501"
fixed <- read_csv(here::here(str_glue("manuscript/tables/clumps_fixed_{metaset}.clumps.csv")))
mrmega <- read_csv(here::here(str_glue("manuscript/tables/clumps_mrmega_{metaset}.clumps.csv")))
susiex <- read_csv(here::here("manuscript/tables/susiex_significant_cs.csv"))
```

Get SNPs for meta-analysis (build 38)
```{r meta}
fixed_snps <- fixed |>
  select(CHROM, POS, ID)
mrmega_snps <- mrmega |>
  mutate(CHROM = if_else(Chromosome == 23, true = "chrX", false = str_c("chr", Chromosome))) |>
  select(CHROM, POS = Position, ID = MarkerName)
```

Lookup build 38 coordinates for SusieX results
```{r susiex, cache = TRUE}
susiex_locs <- snpsById(SNPlocs.Hsapiens.dbSNP150.GRCh38, ids = pull(susiex, SNP))
susiex_snps <- susiex_locs |>
  as.data.frame() |>
  as_tibble() |>
  transmute(CHROM = str_c("chr", as.character(seqnames)),
            POS = pos, 
            ID = RefSNP_id)
```

Merge unique SNPs
```{r merge}
snps <- bind_rows(fixed_snps, mrmega_snps, susiex_snps) |>
  distinct()

dir.create(here::here("results/forest"))
write_tsv(snps, here::here(str_glue("results/forest/{metaset}.snplist")))
```

